theme: jekyll-theme-minimal
title: Karthik Venkatapathy
logo: /assets/img/logo.jpg
github:
  is_project_page: false
  is_user_page: false
  defaults:
    # _docs
    - scope:
        path: ""
        type: cv
      values:
        sidebar:
          nav: "cv"