theme: jekyll-theme-minimal
title: Karthik Venkatapathy
email: vkarthikbalaji@gmail.com
description: >-
  _vkarthikbalaji@gmail.com_
  _+31 (0) 623994658_
  _Driel, Nederland_
github:
  is_project_page: false
  is_user_page: false
