theme: jekyll-theme-minimal
title: Karthik Venkatapathy
email: vkarthikbalaji@gmail.com
description: |
  vkarthikbalaji@gmail.com
  +31 (0) 623994658
  Driel, Nederland
github:
  is_project_page: false
  is_user_page: false
