remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Karthik Venkatapathy
# phone: +31 (0) 623994658
email: vkarthikbalaji@gmail.com
logo: /assets/img/logo.jpg
color-scheme: dark
github:
  is_project_page: false
  is_user_page: false
google_analytics: G-HR5R4KZ27Y
navigation:
  - name: Overview
    link: ./#overview
  - name: Engineering Experience
    link: ./#engineering-experience
  - name: Investing Experience
    link: ./#investing-experience
  - name: Education
    link: ./#education
  - name: Volunteering
    link: ./#volunteering
  - name: Practical
    link: ./#practical
  - name: Personal
    link: ./#personal