remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Karthik Venkatapathy
email: vkarthikbalaji@gmail.com
logo: /assets/img/logo.jpg
github:
  is_project_page: false
  is_user_page: false

navigation:
  - name: Home
    link: ./
    sublist:
      - name: Engineering Experience
        link: ./#engineering-experience
      - name: Investing Experience
        link: ./#investing-experience
      - name: Education
        link: ./#education
      - name: Practical
        link: ./#practical
      - name: Personal
        link: ./#personal